name: Build

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneLinux64
        unityVersion: # Available versions see: https://game.ci/docs/docker/versions
          - 2020.2.0f1
          - 2020.3.4f1
          - 2020.3.22f1
          - 2021.1.28f1
          - 2021.2.0f1

    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: false
          lfs: false

      # Build
      - name: Create license secret key
        id: license
        run: echo "::set-output name=secret_key::UNITY_LICENSE_$(echo ${{ matrix.unityVersion }} | cut -c 1-4)"
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets[steps.license.outputs.secret_key] }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          unityVersion: ${{ matrix.unityVersion }}

      # Notification
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,job,took,eventName,ref,pullRequest
          mention: here
          if_mention: failure
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: always()
